"""Parsing LLM permutation output into a valid ranking.

Open 7B/8B models frequently emit malformed permutations: duplicated
identifiers, missing identifiers, out-of-range identifiers, or prose around
the ranking. We repair the output deterministically and record exactly what
went wrong so we can report parse-quality statistics.

Repair policy (same spirit as the RankGPT reference code):
  1. extract identifiers in the order they appear
  2. drop out-of-range identifiers
  3. drop duplicates, keeping the FIRST occurrence
  4. append any missing identifiers at the end, in their original input order
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Optional

# [3] or [ 3 ]
_BRACKET_RE = re.compile(r"\[\s*(\d+)\s*\]")
# fallback: bare numbers joined by > such as "3 > 1 > 2"
_BARE_CHAIN_RE = re.compile(r"\b\d+\b(?:\s*>\s*\b\d+\b)+")
_BARE_NUM_RE = re.compile(r"\b(\d+)\b")


@dataclass
class ParseResult:
    """Outcome of parsing one LLM response."""

    order: List[int]  # 0-based indices into the candidate list, full permutation
    raw_ids: List[int] = field(default_factory=list)  # 1-based, as emitted
    num_candidates: int = 0
    used_fallback_regex: bool = False
    num_duplicates: int = 0
    num_out_of_range: int = 0
    num_missing: int = 0
    is_empty: bool = False

    @property
    def is_clean(self) -> bool:
        """True iff the model emitted an exact permutation with no repair."""
        return (
            not self.is_empty
            and not self.used_fallback_regex
            and self.num_duplicates == 0
            and self.num_out_of_range == 0
            and self.num_missing == 0
        )

    def to_dict(self) -> dict:
        return {
            "raw_ids": self.raw_ids,
            "num_candidates": self.num_candidates,
            "used_fallback_regex": self.used_fallback_regex,
            "num_duplicates": self.num_duplicates,
            "num_out_of_range": self.num_out_of_range,
            "num_missing": self.num_missing,
            "is_empty": self.is_empty,
            "is_clean": self.is_clean,
        }


def extract_identifiers(text: str) -> tuple[List[int], bool]:
    """Pull the identifier sequence out of raw model text.

    Returns (ids_1based, used_fallback_regex).
    """
    if not text:
        return [], False

    bracketed = [int(m) for m in _BRACKET_RE.findall(text)]
    if bracketed:
        return bracketed, False

    # Fallback 1: a bare chain like "3 > 1 > 2"
    chain = _BARE_CHAIN_RE.search(text)
    if chain:
        return [int(n) for n in _BARE_NUM_RE.findall(chain.group(0))], True

    # Fallback 2: any run of numbers at all (last resort)
    bare = [int(n) for n in _BARE_NUM_RE.findall(text)]
    if bare:
        return bare, True

    return [], False


def parse_permutation(text: str, num_candidates: int) -> ParseResult:
    """Parse and repair one model response into a full permutation.

    Args:
        text: raw text generated by the LLM
        num_candidates: how many passages were in the prompt

    Returns:
        ParseResult whose `order` is always a valid permutation of
        range(num_candidates), even when the model output is garbage
        (in that case it degrades gracefully to the input order).
    """
    raw_ids, used_fallback = extract_identifiers(text)

    seen = set()
    cleaned: List[int] = []
    num_out_of_range = 0
    num_duplicates = 0

    for ident in raw_ids:
        if ident < 1 or ident > num_candidates:
            num_out_of_range += 1
            continue
        if ident in seen:
            num_duplicates += 1
            continue
        seen.add(ident)
        cleaned.append(ident)

    missing = [i for i in range(1, num_candidates + 1) if i not in seen]

    order = [i - 1 for i in cleaned] + [i - 1 for i in missing]

    result = ParseResult(
        order=order,
        raw_ids=raw_ids,
        num_candidates=num_candidates,
        used_fallback_regex=used_fallback,
        num_duplicates=num_duplicates,
        num_out_of_range=num_out_of_range,
        num_missing=len(missing),
        is_empty=len(raw_ids) == 0,
    )

    assert sorted(result.order) == list(range(num_candidates)), "repair produced a non-permutation"
    return result


def aggregate_parse_stats(results: List[ParseResult]) -> dict:
    """Summary statistics over a whole run, for the report table."""
    n = len(results)
    if n == 0:
        return {}
    return {
        "num_windows": n,
        "clean_rate": sum(r.is_clean for r in results) / n,
        "empty_rate": sum(r.is_empty for r in results) / n,
        "fallback_regex_rate": sum(r.used_fallback_regex for r in results) / n,
        "any_duplicate_rate": sum(r.num_duplicates > 0 for r in results) / n,
        "any_missing_rate": sum(r.num_missing > 0 for r in results) / n,
        "any_out_of_range_rate": sum(r.num_out_of_range > 0 for r in results) / n,
        "mean_missing_per_window": sum(r.num_missing for r in results) / n,
        "mean_duplicates_per_window": sum(r.num_duplicates for r in results) / n,
    }
